import type { OracleCategory } from './lexicon.js'

const words = (items: Array<[string, string, string]>) => items.map(([id, label, meaning]) => ({ id, label, meaning }))

export const DEFAULT_ORACLE_CATEGORIES: OracleCategory[] = [
  {
    id: 'judgment',
    label: 'Judgment',
    description: 'What is true, supported, relevant, or decidable?',
    words: words([
      ['yes', 'YES', 'Accept, true, or aligned.'],
      ['no', 'NO', 'Reject, false, or misaligned.'],
      ['partly', 'PARTLY', 'Mixed, incomplete, or conditionally true.'],
      ['unknown', 'UNKNOWN', 'The context does not contain enough information.'],
      ['wrong_question', 'WRONG QUESTION', 'The framing itself prevents a useful answer.'],
      ['probably', 'PROBABLY', 'The available evidence leans toward yes.'],
      ['unlikely', 'UNLIKELY', 'The available evidence leans toward no.'],
      ['contradiction', 'CONTRADICTION', 'Important parts of the context cannot comfortably coexist.'],
      ['irrelevant', 'IRRELEVANT', 'This does not materially affect the answer.'],
      ['undecidable', 'UNDECIDABLE', 'The question cannot be settled from this context.'],
    ]),
  },
  {
    id: 'selection',
    label: 'Selection',
    description: 'Which candidate, position, or combination should win?',
    words: words([
      ['first', 'FIRST', 'Choose the earliest, primary, or foundational option.'],
      ['last', 'LAST', 'Choose the final, latest, or most mature option.'],
      ['middle', 'MIDDLE', 'Avoid either extreme.'],
      ['many', 'MANY', 'Several options belong in the answer.'],
      ['none', 'NONE', 'Reject the available choices.'],
      ['closest', 'CLOSEST', 'Choose the nearest workable approximation.'],
      ['outlier', 'OUTLIER', 'The unusual exception matters most.'],
      ['default', 'DEFAULT', 'Use the established or conventional path.'],
      ['alternative', 'ALTERNATIVE', 'Look beyond the apparent favorites.'],
      ['pair', 'PAIR', 'Two choices belong together.'],
    ]),
  },
  {
    id: 'movement',
    label: 'Movement',
    description: 'In which direction should the situation move?',
    words: words([
      ['begin', 'BEGIN', 'Initiate the first meaningful step.'],
      ['continue', 'CONTINUE', 'Stay on the current course.'],
      ['stop', 'STOP', 'Discontinue or refuse.'],
      ['return', 'RETURN', 'Revisit an earlier state or decision.'],
      ['leap', 'LEAP', 'Make the larger, bolder move.'],
      ['pause', 'PAUSE', 'Stop temporarily without abandoning the path.'],
      ['approach', 'APPROACH', 'Move closer or become more involved.'],
      ['withdraw', 'WITHDRAW', 'Create distance or reduce involvement.'],
      ['persist', 'PERSIST', 'Continue despite resistance.'],
      ['redirect', 'REDIRECT', 'Keep the goal, but change the path.'],
    ]),
  },
  {
    id: 'transformation',
    label: 'Transformation',
    description: 'What operation should be performed on the situation?',
    words: words([
      ['add', 'ADD', 'Introduce something that is missing.'],
      ['remove', 'REMOVE', 'Eliminate something unnecessary or harmful.'],
      ['replace', 'REPLACE', 'Exchange the current thing for another.'],
      ['combine', 'COMBINE', 'Merge ideas, paths, or objects.'],
      ['separate', 'SEPARATE', 'Untangle things that should not be coupled.'],
      ['simplify', 'SIMPLIFY', 'Reduce internal complexity.'],
      ['expand', 'EXPAND', 'Introduce breadth, capacity, or possibility.'],
      ['reorder', 'REORDER', 'Preserve the pieces, but change their sequence.'],
      ['translate', 'TRANSLATE', 'Express the same thing in another form.'],
      ['reverse', 'REVERSE', 'Invert the direction, logic, or assumption.'],
    ]),
  },
  {
    id: 'magnitude',
    label: 'Magnitude',
    description: 'How much, how broadly, or how intensely?',
    words: words([
      ['more', 'MORE', 'Increase it.'],
      ['less', 'LESS', 'Reduce it.'],
      ['enough', 'ENOUGH', 'The current amount is sufficient.'],
      ['all', 'ALL', 'Apply it completely.'],
      ['minimum', 'MINIMUM', 'Do the smallest viable version.'],
      ['maximum', 'MAXIMUM', 'Push toward the practical limit.'],
      ['balance', 'BALANCE', 'Redistribute until forces are comparable.'],
      ['concentrate', 'CONCENTRATE', 'Place resources into fewer things.'],
      ['distribute', 'DISTRIBUTE', 'Spread resources across several things.'],
      ['threshold', 'THRESHOLD', 'Act only after a meaningful boundary is crossed.'],
    ]),
  },
  {
    id: 'time',
    label: 'Time',
    description: 'When, in what order, and for how long?',
    words: words([
      ['now', 'NOW', 'Act immediately.'],
      ['later', 'LATER', 'Defer deliberately.'],
      ['slowly', 'SLOWLY', 'Proceed through gradual accumulation.'],
      ['quickly', 'QUICKLY', 'Compress the process.'],
      ['repeat', 'REPEAT', 'Cycle until the condition changes.'],
      ['before', 'BEFORE', 'Something else must happen first.'],
      ['after', 'AFTER', 'Wait for a preceding event.'],
      ['temporary', 'TEMPORARY', 'Use a reversible intermediate state.'],
      ['permanent', 'PERMANENT', 'Optimize for lasting consequences.'],
      ['moment', 'MOMENT', 'Timing or opportunity determines the answer.'],
    ]),
  },
  {
    id: 'attention',
    label: 'Attention',
    description: 'Where should understanding and observation be directed?',
    words: words([
      ['look_closer', 'LOOK CLOSER', 'Inspect the details.'],
      ['zoom_out', 'ZOOM OUT', 'Consider the larger system.'],
      ['look_behind', 'LOOK BEHIND', 'Find the hidden cause.'],
      ['look_ahead', 'LOOK AHEAD', 'Consider the consequences.'],
      ['look_elsewhere', 'LOOK ELSEWHERE', 'The important thing is outside the current frame.'],
      ['compare', 'COMPARE', 'Meaning will emerge through contrast.'],
      ['measure', 'MEASURE', 'Replace impressions with evidence.'],
      ['listen', 'LISTEN', 'Attend to signals currently being ignored.'],
      ['name_it', 'NAME IT', 'Make the vague or implicit thing explicit.'],
      ['ignore', 'IGNORE', 'Deny an unimportant signal further attention.'],
    ]),
  },
  {
    id: 'relationship',
    label: 'Relationship',
    description: 'How do important things connect or affect one another?',
    words: words([
      ['same', 'SAME', 'The things are equivalent, analogous, or matching.'],
      ['opposite', 'OPPOSITE', 'Invert the assumption or relationship.'],
      ['cause', 'CAUSE', 'This produces the result.'],
      ['symptom', 'SYMPTOM', 'This is an effect, not the source.'],
      ['dependence', 'DEPENDENCE', 'The answer hinges on something else.'],
      ['conflict', 'CONFLICT', 'Two forces are actively incompatible.'],
      ['reinforcement', 'REINFORCEMENT', 'The elements strengthen one another.'],
      ['sequence', 'SEQUENCE', 'The relationship is primarily about order.'],
      ['structural_boundary', 'STRUCTURAL BOUNDARY', 'A distinction between concepts or systems must be preserved.'],
      ['feedback', 'FEEDBACK', 'The result returns to influence its cause.'],
    ]),
  },
  {
    id: 'strategy',
    label: 'Strategy',
    description: 'What general method offers the strongest path forward?',
    words: words([
      ['simple', 'SIMPLE', 'Choose fewer moving pieces.'],
      ['safe', 'SAFE', 'Preserve reversibility and limit damage.'],
      ['bold', 'BOLD', 'Favor potential over protection.'],
      ['test', 'TEST', 'Obtain evidence through a small experiment.'],
      ['adapt', 'ADAPT', 'Decide incrementally from feedback.'],
      ['prepare', 'PREPARE', 'Improve readiness before acting.'],
      ['commit', 'COMMIT', 'Stop preserving alternatives.'],
      ['negotiate', 'NEGOTIATE', 'Seek a workable exchange.'],
      ['bypass', 'BYPASS', 'Avoid the obstacle instead of defeating it.'],
      ['rebuild', 'REBUILD', 'The foundation cannot support the desired result.'],
    ]),
  },
  {
    id: 'meaning',
    label: 'Human meaning',
    description: 'Which human motive, value, or emotional movement matters most?',
    words: words([
      ['desire', 'DESIRE', 'Follow what is genuinely wanted.'],
      ['duty', 'DUTY', 'Follow the obligation.'],
      ['fear', 'FEAR', 'Fear is governing the situation.'],
      ['care', 'CARE', 'Protect the person or thing that matters.'],
      ['release', 'RELEASE', 'Stop controlling, pursuing, or carrying it.'],
      ['trust', 'TRUST', 'Accept uncertainty or another person’s agency.'],
      ['personal_boundary', 'PERSONAL BOUNDARY', 'Protect autonomy, limits, or self-respect.'],
      ['connect', 'CONNECT', 'Move toward understanding or companionship.'],
      ['express', 'EXPRESS', 'Reveal what has remained internal.'],
      ['accept', 'ACCEPT', 'Stop requiring reality to be different first.'],
    ]),
  },
]
